Linux_task:
  container:
    matrix:
      - image: ruby:3.3-bookworm
      - image: ruby:3.2-bookworm
      - image: ruby:3.1-bookworm
  script:
    - ruby --version
    - rake test

macOS_task:
  macos_instance:
    image: ghcr.io/cirruslabs/macos-sonoma-base:latest
  env:
    matrix:
      # https://formulae.brew.sh/formula/ruby
      - RUBY: 3.3
      - RUBY: 3.2
      - RUBY: 3.1
  brew_update_script:
    - brew update
  brew_install_script:
    # Per the pyenv homebrew recommendations.
    #  https://github.com/pyenv/pyenv/wiki#suggested-build-environment
    - brew install ruby@${RUBY}
  script:
    - ruby --version
    - rake test

# TODO: Test on Windows
Windows_task:
  windows_container:
    image: cirrusci/windowsservercore:2019
  env:
    matrix:
      - RUBY: 3.3.0.1
      - RUBY: 3.2.3.1
      - RUBY: 3.1.3.1
  ruby_install_script:
    - cinst ruby --version=%RUBY% --package-parameters="/InstallDir:C:\Ruby"
    - cinst msys2 --params "/NoUpdate"
    # NOTE: This overwrites the %RUBY% environment variable.
    - Update-SessionEnvironment
    - ridk install 2 3
  script:
    - ruby --version
    - rake test

success_task:
  name: CI success
  container: {image: "busybox"}
  depends_on:
    - Linux
    - macOS
    - Windows
